import type { Topic } from './questions.ts';

export type ClueSubject = {
  id: string;
  topic: Topic;
  answer: string;
  clues: readonly [string, string, string, string, string];
  explanation: string;
  funFact: string;
  sourceUrl: string;
};

const characters = 'https://mario.nintendo.com/characters/';
const courses = 'https://en-americas-support.nintendo.com/app/answers/detail/a_id/57858/';

export const CLUE_SUBJECTS: readonly ClueSubject[] = [
  { id: 'char-mario', topic: 'mario', answer: 'Mario', clues: ['I often help friends in the Mushroom Kingdom.', 'I enjoy many sports, including kart racing.', 'I wear blue overalls and a red cap.', 'My brother wears green and is named Luigi.', 'My name begins with M.'], explanation: 'Mario is the Mushroom Kingdom hero and Luigi’s brother. His jumping skills help him through many adventures.', funFact: 'Nintendo says Mario is a plumber, but also a jack of all trades.', sourceUrl: characters },
  { id: 'char-luigi', topic: 'mario', answer: 'Luigi', clues: ['I am one of the Mushroom Kingdom heroes.', 'Ghosts can make me nervous.', 'I can jump higher than my brother.', 'My brother Mario wears red; I wear green.', 'My name begins with L.'], explanation: 'Luigi is Mario’s brother. He is taller, wears green and can jump higher than Mario.', funFact: 'Nintendo points out that Luigi’s moustache has a different shape from Mario’s.', sourceUrl: characters },
  { id: 'char-peach', topic: 'mario', answer: 'Princess Peach', clues: ['I often join Mario and friends in sports.', 'I enjoy baking and cooking.', 'I wear a signature pink dress.', 'I am the princess of the Mushroom Kingdom.', 'My name begins with P.'], explanation: 'Princess Peach looks after the Mushroom Kingdom. She also joins Mario in adventures and sports.', funFact: 'Peach and Mario are good friends who help each other.', sourceUrl: characters },
  { id: 'char-yoshi', topic: 'mario', answer: 'Yoshi', clues: ['I am a kind, carefree friend of Mario.', 'Members of my kind can be several colours.', 'I come from an island named after me.', 'I use my long tongue to turn food and enemies into eggs.', 'My name begins with Y.'], explanation: 'Yoshi uses his tongue to grab fruit and enemies, then can make eggs to throw.', funFact: 'Nintendo lists red, blue, pink and yellow Yoshis as well as green ones.', sourceUrl: characters },
  { id: 'char-bowser', topic: 'mario', answer: 'Bowser', clues: ['I often cause trouble in the Mushroom Kingdom.', 'Goombas, Koopas and Shy Guys can work for me.', 'I am very strong and can breathe fire.', 'I am King of the Koopas and Mario’s archrival.', 'My name begins with B.'], explanation: 'Bowser leads the Koopas and repeatedly challenges Mario in the Mushroom Kingdom.', funFact: 'Bowser Jr. is Bowser’s only son, according to Nintendo’s character guide.', sourceUrl: characters },
  { id: 'char-daisy', topic: 'mario', answer: 'Daisy', clues: ['I like playing sports with Mario and friends.', 'I am cheerful and energetic.', 'I wear yellow and flower-shaped accessories.', 'I am the princess of Sarasaland.', 'My name begins with D.'], explanation: 'Daisy is the princess of Sarasaland. She brings lots of energy to Mario’s sports games.', funFact: 'Sarasaland is not the same kingdom as Peach’s Mushroom Kingdom.', sourceUrl: characters },
  { id: 'char-wario', topic: 'mario', answer: 'Wario', clues: ['I like making money.', 'I also love garlic.', 'I wear purple overalls and a yellow hat.', 'I call myself Mario’s rival and have a zigzag moustache.', 'My name begins with W.'], explanation: 'Wario styles himself as Mario’s rival. His yellow hat and purple overalls stand out.', funFact: 'Nintendo says Wario and Mario have known each other since they were babies.', sourceUrl: characters },
  { id: 'char-rosalina', topic: 'mario', answer: 'Rosalina', clues: ['I sometimes join Mario and friends on adventures.', 'My home is among the stars.', 'My family includes small star-like creatures.', 'I am the adoptive mother of the Lumas.', 'My name begins with R.'], explanation: 'Rosalina cares for the Lumas. Nintendo describes her as mysterious but kind-hearted.', funFact: 'Rosalina travels across the galaxy with her Luma family.', sourceUrl: characters },

  { id: 'track-coconut', topic: 'kart', answer: 'Coconut Mall', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name suggests somewhere people might shop.', 'I first appeared as a Wii course.', 'I finish the Golden Dash Cup.', 'My name begins with C.'], explanation: 'Coconut Mall is the fourth Golden Dash Cup course in the Booster Course Pass.', funFact: 'The same cup begins with Paris Promenade.', sourceUrl: courses },
  { id: 'track-waluigi', topic: 'kart', answer: 'Waluigi Pinball', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name belongs to one of Mario’s rivals.', 'I first appeared as a Nintendo DS course.', 'I finish the Turnip Cup.', 'My name begins with W.'], explanation: 'Waluigi Pinball is the fourth Turnip Cup course in the Booster Course Pass.', funFact: 'The Turnip Cup also contains Kalimari Desert.', sourceUrl: courses },
  { id: 'track-maple', topic: 'kart', answer: 'Maple Treeway', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name suggests trees and a route through them.', 'I first appeared as a Wii course.', 'I finish the Rock Cup.', 'My name begins with M.'], explanation: 'Maple Treeway is a returning Wii track and the fourth course in the Rock Cup.', funFact: 'London Loop opens the Rock Cup.', sourceUrl: courses },
  { id: 'track-rome', topic: 'kart', answer: 'Rome Avanti', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name points to a real-world capital city.', 'I am listed as a Tour course.', 'I open the Acorn Cup.', 'My name begins with R.'], explanation: 'Rome Avanti opens the Acorn Cup in the final Booster Course Pass wave.', funFact: 'The Acorn Cup ends with Piranha Plant Cove.', sourceUrl: courses },
  { id: 'track-daisy', topic: 'kart', answer: 'Daisy Cruiser', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name includes a princess’s name.', 'I first appeared as a GameCube course.', 'I am second in the Feather Cup.', 'My name begins with D.'], explanation: 'Daisy Cruiser is a GameCube track placed second in the Feather Cup.', funFact: 'Wii Moonview Highway follows Daisy Cruiser in that cup.', sourceUrl: courses },
  { id: 'track-ninja', topic: 'kart', answer: 'Ninja Hideaway', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name suggests a secret place.', 'I am listed as a Tour course.', 'I finish the Lucky Cat Cup.', 'My name begins with N.'], explanation: 'Ninja Hideaway closes the Lucky Cat Cup in the Booster Course Pass.', funFact: 'Tokyo Blur opens the Lucky Cat Cup.', sourceUrl: courses },
  { id: 'track-sundae', topic: 'kart', answer: 'Sky-High Sundae', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name suggests something sweet.', 'My name also hints at being high above the ground.', 'I finish the Propeller Cup.', 'My name begins with S.'], explanation: 'Sky-High Sundae is the fourth course in the Propeller Cup.', funFact: 'The same cup also contains Mushroom Gorge.', sourceUrl: courses },
  { id: 'track-piranha', topic: 'kart', answer: 'Piranha Plant Cove', clues: ['I am an extra course in Mario Kart 8 Deluxe.', 'My name suggests a sheltered stretch of water.', 'My name includes a familiar toothy Mario enemy.', 'I finish the Acorn Cup.', 'My name begins with P.'], explanation: 'Piranha Plant Cove is the last Acorn Cup course in the Booster Course Pass.', funFact: 'The Acorn Cup is part of the sixth and final pass wave.', sourceUrl: courses },
];
