import type { Category, Difficulty, Topic, TriviaQuestion } from './questions.ts';

// Pilot batch: each tested fact is new to the quiz bank. Stable descriptive IDs
// keep player history intact when more records are added or reordered.
export const GAMEPLAY_SOURCES = {
  odyssey: 'https://www.nintendo.com/en-gb/Games/Nintendo-Switch-games/Super-Mario-Odyssey-1173332.html',
  fury: 'https://www.nintendo.com/sg/switch/auzp/furyworld/index.html',
  world: 'https://www.nintendo.com/us/whatsnew/mario-kart-world-direct-revs-up-new-details-on-the-biggest-mario-kart-ever-coming-to-nintendo-switch-2-at-launch/',
  wave2: 'https://www.nintendo.com/us/whatsnew/mario-kart-8-deluxe-booster-course-pass-wave-2-approaches-the-starting-line-on-aug-4/',
  uDeluxe: 'https://www.nintendo.com/en-gb/Games/Nintendo-Switch-games/New-Super-Mario-Bros-U-Deluxe-1438640.html',
  world3d: 'https://www.nintendo.com/sg/switch/auzp/3dworld/index.html',
  odysseyExplore: 'https://supermario.nintendo.com/explore/',
  kartBattle: 'https://mariokart8.nintendo.com/',
} as const;

type Entry = readonly [id: string, topic: Topic, difficulty: Difficulty, category: Category,
  prompt: string, answer: string, wrong1: string, wrong2: string, wrong3: string,
  explanation: string, funFact: string, source: keyof typeof GAMEPLAY_SOURCES];

const entries: readonly Entry[] = [
  ['ud-acorn', 'mario', 'explorer', 'power-ups',
    'Which item enables Flying Squirrel Mario in New Super Mario Bros. U Deluxe?', 'Super Acorn', 'Super Leaf', 'Cape Feather', 'Super Bell',
    'Gliding helps you cover a gap without dropping straight down. You can also briefly grip a wall.',
    'This adventure includes snowy areas as well as deserts.', 'uDeluxe'],
  ['ud-crown', 'mario', 'scientist', 'power-ups',
    'Who can use the Super Crown in New Super Mario Bros. U Deluxe?', 'Toadette', 'Toad', 'Luigi', 'Nabbit',
    'It transforms her into Peachette, with a double jump and a slower fall.',
    'Peachette can bounce back out of a pit.', 'uDeluxe'],
  ['ud-mini-water', 'mario', 'professor', 'power-ups',
    'In New Super Mario Bros. U Deluxe, which transformation can run on water?', 'Mini Mario', 'Fire Mario', 'Super Mario', 'Flying Squirrel Mario',
    'The tiny form changes movement as well as size, opening routes through very small gaps.',
    'Mini Mario can jump higher too.', 'uDeluxe'],
  ['ud-propeller-reset', 'mario', 'professor', 'games',
    'In New Super Mario Bros. U Deluxe, what restores another Propeller Jump?', 'Touching the ground', 'Collecting a coin', 'Passing an enemy', 'Releasing the jump button',
    'You must land before soaring again. Plan somewhere safe to touch down.',
    'The propeller also slows your descent.', 'uDeluxe'],
  ['3dw-rescue', 'mario', 'explorer', 'characters',
    'Who needs rescuing in Super Mario 3D World?', 'The Sprixie Princesses', 'The Lumas', 'The Broodals', 'The Koopalings',
    'Bowser captures these rulers, drawing Mario and friends into the Sprixie Kingdom.',
    'Clear pipes lead into this adventure.', 'world3d'],
  ['3dw-float', 'mario', 'explorer', 'characters',
    'Which starting character has a floating jump in Super Mario 3D World?', 'Peach', 'Mario', 'Luigi', 'Toad',
    'Floating gives her extra time in the air to cross a gap. Characters differ even without power-ups.',
    'Toad’s strength is his quick dash.', 'world3d'],
  ['3dw-cherry', 'mario', 'scientist', 'power-ups',
    'Which item creates extra copies of your character in Super Mario 3D World?', 'Double Cherry', 'Mega Mushroom', 'Super Leaf', 'Super Bell',
    'You control more than one copy instead of simply changing costume or size.',
    'The game also includes a giant Mega form.', 'world3d'],
  ['3dw-rosalina', 'mario', 'professor', 'characters',
    'Which special move belongs to Rosalina in Super Mario 3D World?', 'Spin attack', 'Floating jump', 'Flutter jump', 'Ground-pound jump',
    'Her spinning attack gives her a different way to handle enemies, beyond the starting characters’ movement traits.',
    'She is an unlockable character, not a starting choice.', 'world3d'],
  ['odyssey-shop', 'mario', 'explorer', 'games',
    'Where can Mario buy outfits in Super Mario Odyssey?', 'Crazy Cap', 'Toad House', 'Yoshi’s', 'Funky’s Fly ’n’ Buy',
    'These shops let you spend coins collected while exploring, rather than relying only on hidden items.',
    'They also sell souvenirs for the airship.', 'odysseyExplore'],
  ['odyssey-regional', 'mario', 'scientist', 'games',
    'Which currency pays for certain local souvenirs in Super Mario Odyssey?', 'Regional Coins', 'Star Bits', 'Flower Coins', 'Dragon Coins',
    'Some purchases need that kingdom’s special coins, so ordinary gold coins cannot pay for everything.',
    'Stickers decorate the outside of the Odyssey.', 'odysseyExplore'],
  ['odyssey-outfits', 'mario', 'scientist', 'games',
    'What can some Super Mario Odyssey outfits do besides change Mario’s appearance?', 'Grant access to special places', 'Increase jump height', 'Make enemies harmless', 'Double every coin collected',
    'Clothing can open an opportunity to explore, without granting a new power.',
    'The shops also sell Life-Up Hearts.', 'odysseyExplore'],
  ['odyssey-assist', 'mario', 'explorer', 'games',
    'What does Assist Mode add in Super Mario Odyssey?', 'More health and guiding arrows', 'Infinite coins and faster running', 'Automatic jumps and captures', 'Extra kingdoms and costumes',
    'It supports exploration while leaving you in control of Mario.',
    'You can still shop and customise the airship.', 'odysseyExplore'],
  ['battle-renegade', 'kart', 'explorer', 'games',
    'What catches the opposing team in Mario Kart 8 Deluxe’s Renegade Roundup?', 'Piranha Plants', 'Fishing rods', 'Chain Chomps', 'Boomerangs',
    'One team captures the other in a cops-and-robbers contest, rather than racing for a finish line.',
    'Captured racers are sent to jail.', 'kartBattle'],
  ['battle-shine', 'kart', 'scientist', 'games',
    'What is the aim of Shine Thief in Mario Kart 8 Deluxe?', 'Hold the Shine Sprite for a count of 20', 'Collect 20 separate Shine Sprites', 'Finish 20 laps', 'Break 20 item boxes',
    'Keeping possession matters: simply touching the prize is not enough to win.',
    'Battle mode also includes a coins-only collection contest.', 'kartBattle'],
  ['battle-urchin', 'kart', 'professor', 'tracks',
    'Which Nintendo game inspired Mario Kart 8 Deluxe’s Urchin Underpass arena?', 'Splatoon', 'ARMS', 'Pikmin', 'Star Fox',
    'The arena adapts a Turf War setting for kart battles, bringing another series into Mario Kart.',
    'Lunar Colony, another battle arena, is on the moon.', 'kartBattle'],
  ['battle-bombs', 'kart', 'professor', 'games',
    'What restricts your attacks in Mario Kart 8 Deluxe’s Bob-omb Blast?', 'Only Bob-ombs are used', 'Only shells are used', 'Items are disabled', 'Only contact causes damage',
    'You still compete to pop balloons, but the limited weapon choice changes how you attack.',
    'Battle Stadium includes an anti-gravity ring.', 'kartBattle'],
  ['odyssey-cappy', 'mario', 'explorer', 'characters',
    'Who becomes Mario’s hat-shaped partner in Super Mario Odyssey?', 'Cappy', 'Luma', 'FLUDD', 'Prince Florian',
    'Cappy takes the shape of Mario’s familiar cap. His Capture ability lets Mario control enemies and use their abilities.',
    'Cappy comes from a place called the Cap Kingdom.', 'odyssey'],
  ['fury-partner', 'mario', 'explorer', 'characters',
    'Who helps Mario bring Bowser back to normal in Bowser’s Fury?', 'Bowser Jr.', 'Luigi', 'Toad', 'Kamek',
    'Bowser Jr. asks his usual enemy for help. A second player can control him while the first plays Mario.',
    'Solo players can choose how much assistance Junior gives.', 'fury'],
  ['odyssey-fuel', 'mario', 'scientist', 'games',
    'What powers the Odyssey airship so Mario can reach new kingdoms?', 'Power Moons', 'Grand Stars', 'Cat Shines', 'Wonder Seeds',
    'Collecting Power Moons powers up the ship for the next journey. Exploring each kingdom helps you find more fuel.',
    'The game shares its name with Mario’s airship.', 'odyssey'],
  ['fury-bell', 'mario', 'scientist', 'power-ups',
    'Which power-up lets Mario face Fury Bowser at a similar giant size?', 'Giga Bell', 'Mega Mushroom', 'Super Bell', 'Super Star',
    'The Giga Bell transforms him into Giga Cat Mario. This is a much bigger transformation than the ordinary cat form.',
    'Cat Shines help clear the dark goop covering the bell.', 'fury'],
  ['odyssey-planners', 'mario', 'professor', 'baddies',
    'Which group does Bowser hire to arrange his wedding in Super Mario Odyssey?', 'The Broodals', 'The Koopalings', 'The Hammer Bros.', 'The Shy Guys',
    'The Broodals work on Bowser’s wedding plans and stand in Mario’s way as he tries to stop the ceremony.',
    'Bowser travels around the world preparing for the wedding.', 'odyssey'],
  ['fury-cats', 'mario', 'professor', 'games',
    'What happens to Lake Lapcat’s friendly cats when Fury Bowser awakens?', 'They rush at Mario to attack', 'They hide inside bells', 'They turn into Cat Shines', 'They fall asleep until dawn',
    'The cats are caught up in the frenzy too. Even familiar animals become a danger during Bowser’s rampage.',
    'The peaceful setting changes to darkness and heavy rain.', 'fury'],
  ['world-steering', 'kart', 'explorer', 'games',
    'Which Mario Kart World assistance option helps keep your kart on the course?', 'Smart Steering', 'Auto-Accelerate', 'Tilt Controls', 'Rewind',
    'Smart Steering helps with staying on track. Auto-Accelerate handles acceleration instead, so the two options solve different problems.',
    'You can switch these driving aids on or off.', 'world'],
  ['kalimari-train', 'kart', 'explorer', 'tracks',
    'Which moving obstacle crosses the route on N64 Kalimari Desert in Mario Kart 8 Deluxe?', 'A steam train', 'A giant Chain Chomp', 'A tram', 'A row of bouncing boulders',
    'A locomotive crosses the racers’ path. Watch for it rather than treating the track as an empty stretch of desert.',
    'This returning course began on Nintendo 64.', 'wave2'],
  ['world-kamek', 'kart', 'scientist', 'power-ups',
    'Which Mario Kart World item calls on magic to transform rival racers?', 'Kamek', 'Boo', 'Lightning', 'Blooper',
    'Kamek brings magical transformations into the race. That is different from Boo’s ghostly tricks or Blooper’s ink.',
    'Racers further behind are more likely to receive powerful items.', 'world'],
  ['gorge-bouncing', 'kart', 'scientist', 'tracks',
    'What do racers bounce on to cross gaps in Wii Mushroom Gorge?', 'Giant mushrooms', 'Floating balloons', 'Spring-loaded barrels', 'Moving lily pads',
    'The mushrooms act as springy platforms. Getting across a gap also means lining up a safe landing.',
    'Part of the route passes through an underground cavern.', 'wave2'],
  ['world-warp', 'kart', 'professor', 'games',
    'In Mario Kart World Free Roam with friends, how can you join someone far away?', 'Warp to them using the map', 'Wait for the next Grand Prix', 'Win a race to their location', 'Use a Bullet Bill to follow them',
    'The map lets you find friends and warp to them. You can meet up without driving the whole distance first.',
    'Free Roam also lets the group take in-game photos.', 'world'],
  ['circuit3-pipes', 'kart', 'professor', 'tracks',
    'Which obstacles accompany the tight bends on SNES Mario Circuit 3?', 'Warp Pipes', 'Rolling snowballs', 'Falling Thwomps', 'Moving cars',
    'The pipes are obstacles to steer around while taking the bends. The course returns from the original Super Mario Kart.',
    'Its original console was the Super Nintendo.', 'wave2'],
];

export const GAMEPLAY_QUESTIONS: readonly TriviaQuestion[] = entries.map(([id, topic, difficulty, category, prompt, answer, a, b, c, explanation, funFact, source]) => ({
  id: `gameplay-${id}`, knowledgeId: `gameplay-${id}`, topic, difficulty, category,
  prompt, answer, choices: [answer, a, b, c], explanation, funFact,
  sourceUrl: GAMEPLAY_SOURCES[source],
  sourceReview: { checkedOn: '2026-10-04', status: 'source-checked', gameVersion: ({ odyssey: 'Super Mario Odyssey', fury: 'Bowser’s Fury', world: 'Mario Kart World', wave2: 'Mario Kart 8 Deluxe — Booster Course Pass Wave 2', uDeluxe: 'New Super Mario Bros. U Deluxe', world3d: 'Super Mario 3D World — Nintendo Switch', odysseyExplore: 'Super Mario Odyssey', kartBattle: 'Mario Kart 8 Deluxe — Battle mode' })[source] },
}));

export const GAMEPLAY_REVIEW = { checkedOn: '2026-10-04', status: 'source-checked', humanPlaytest: 'pending' } as const;
