import { QUESTIONS, type Difficulty, type TriviaQuestion } from './questions.ts';

// Matching-specific wording of existing sourced knowledge, not new trivia facts.
// Difficulty is inherited from the source record: larger boards never borrow
// questions above the selected knowledge level just to fill space.
const CLUES: Readonly<Record<string, string>> = {
  'mario-explorer-1': 'Mario’s brother, who wears green.',
  'mario-explorer-2': 'Princess of the Mushroom Kingdom.',
  'mario-explorer-3': 'King of the Koopas.',
  'mario-explorer-5': 'Travels with the star-like Lumas.',
  'mario-explorer-6': 'Wears a face covering with a fearsome mouth drawn on it.',
  'mario-explorer-7': 'Mario’s rival in a yellow hat and purple overalls.',
  'mario-explorer-8': 'Wario’s partner and Luigi’s self-declared rival.',
  'mario-explorer-9': 'A Mushroom Kingdom resident who helps Princess Peach.',
  'mario-explorer-10': 'Princess of Sarasaland.',
  'expanded-1': 'Wonder power-up that gives Mario a trunk.',
  'expanded-2': 'Wonder power-up that creates bubbles to jump on.',
  'expanded-4': 'Mario enemy that carries a shell on its back.',
  'expanded-5': 'A shy ghost that covers its eyes when spotted.',
  'expanded-6': 'The first Mario game built around creating your own levels.',
  'expanded-7': 'Mario’s friend who grabs enemies with a long tongue.',
  'fresh-1': 'The kingdom visited in Super Mario Bros. Wonder.',
  'fresh-3': 'Wonder badge that helps you float over gaps.',
  'fresh-4': 'Wonder character who avoids damage from enemies.',
  'fresh-5': 'Power-up that gives Mario a cat form in Super Mario 3D World.',
  'fresh-6': 'Squared paper used to plan the first Super Mario Bros.',
  'kart-explorer-1': 'Mario Kart World course with a cinema-themed name.',
  'kart-explorer-2': 'Mario Kart World course described as having snowy trails.',
  'kart-explorer-3': 'Mario Kart World course with modern city streets.',
  'kart-explorer-4': 'World mode for exploring without entering a race.',
  'kart-explorer-5': 'World rally mode that eliminates racers at checkpoints.',
  'kart-explorer-7': 'Returning Wii course named after a shopping centre.',
  'kart-explorer-8': 'Returning DS course named after an arcade ball game.',
  'kart-explorer-9': 'Returning N64 course with a chocolate-themed mountain name.',
  'kart-explorer-10': 'World mode for racing against the clock.',
  'expanded-22': 'Track that debuted in Mario Kart 8 Deluxe’s second DLC wave, before coming to Tour.',
  'expanded-23': 'Tour course with routes inside a manor and across its tiled rooftops.',
  'expanded-24': 'Mario Kart 8 Deluxe item that gives a short speed boost.',
  'expanded-25': 'Mario Kart 8 Deluxe item that sprays ink on racers ahead.',
  'expanded-28': 'Mario Kart game with an explorable, connected Free Roam world.',
  'fresh-19': 'Collect these to win Coin Runners in Mario Kart World.',
  'fresh-20': 'Pop these to attack opponents in Balloon Battle.',
  'fresh-21': 'The farm animal highlighted as a surprising racer in World.',
  'fresh-22': 'One effect of ordering Dash Food in Mario Kart World.',
  'fresh-23': 'GameCube mountain course brought back in the Acorn Cup.',
  'fresh-24': 'DS garden course brought back in the Moon Cup.',
  'mario-scientist-1': 'Original console for Super Mario 64.',
  'mario-scientist-2': 'Original console for Super Mario Sunshine.',
  'mario-scientist-3': 'Original console for Super Mario Galaxy.',
  'mario-scientist-4': 'Original system for Super Mario Odyssey.',
  'mario-scientist-5': 'Handheld that first hosted Super Mario 3D Land.',
  'mario-scientist-6': 'Original console for Super Mario Maker.',
  'mario-scientist-7': 'Handheld that first hosted Super Mario Land.',
  'mario-scientist-8': 'Original console for Super Mario World.',
  'mario-scientist-10': 'Nintendo’s platform category for Super Mario Run.',
  'expanded-8': 'Wonder power-up for burrowing into some floors and ceilings.',
  'expanded-9': 'Wonder power-up that throws bouncing fireballs.',
  'expanded-10': 'Masked troublemaker playable in Super Mario Party.',
  'expanded-11': 'Helmet-wearing enemy that throws hammers.',
  'expanded-12': 'Wii adventure set across the galaxy.',
  'expanded-13': 'Handheld that first hosted New Super Mario Bros.',
  'fresh-9': 'Number of friends who can join you locally in Wonder.',
  'fresh-11': 'Mario level-building sequel released in 2019.',
  'kart-scientist-1': 'MK8 Deluxe cup containing Wii Coconut Mall.',
  'kart-scientist-2': 'MK8 Deluxe cup containing DS Waluigi Pinball.',
  'kart-scientist-3': 'MK8 Deluxe cup containing Wii Maple Treeway.',
  'kart-scientist-4': 'MK8 Deluxe cup containing GCN Daisy Cruiser.',
  'kart-scientist-5': 'MK8 Deluxe cup containing Tour Tokyo Blur.',
  'kart-scientist-6': 'MK8 Deluxe cup containing Wii Rainbow Road.',
  'kart-scientist-7': 'MK8 Deluxe cup containing DS Peach Gardens.',
  'kart-scientist-8': 'MK8 Deluxe cup containing GBA Riverside Park.',
  'kart-scientist-9': 'MK8 Deluxe cup containing Tour Singapore Speedway.',
  'kart-scientist-10': 'World move that can launch a kart onto rails or wall rides.',
  'expanded-29': 'MK8 Deluxe cup containing GBA Snow Land.',
  'expanded-30': 'MK8 Deluxe cup containing GBA Sunset Wilds.',
  'expanded-31': 'MK8 Deluxe item whose blast can knock nearby items away.',
  'expanded-32': 'MK8 Deluxe item that adds two coins to your total.',
  'fresh-28': 'Racer added in Booster Course Pass Wave 4.',
  'mario-professor-1': 'GameCube adventure released before Super Mario Galaxy.',
  'mario-professor-3': 'Mario’s 2013 Wii U adventure, not the similarly named 3DS game.',
  'mario-professor-4': 'Wii platform game released between Galaxy and Galaxy 2.',
  'mario-professor-6': 'Mobile Mario game placed immediately before Odyssey on Nintendo’s timeline.',
  'mario-professor-7': 'Mario’s taller brother, known for jumping higher.',
  'mario-professor-8': 'The Lumas’ adoptive mother.',
  'mario-professor-9': 'Mario’s rival with a taste for garlic.',
  'expanded-15': 'Wonder transformation that can water a wilted flower bud.',
  'expanded-16': 'Wonder transformation that makes bubbles to both sides during a spin jump.',
  'expanded-17': 'Mole character playable in Super Mario Party.',
  'expanded-18': 'Skeletal baddie that can fall apart and recover.',
  'expanded-19': 'Mario’s name in the 1981 Donkey Kong arcade game.',
  'expanded-21': 'Character whose red necktie carries his initials.',
  'fresh-14': 'Name Miyamoto considered for Mario before settling on his familiar name.',
  'fresh-15': 'A charging herd event triggered by a Wonder Flower.',
  'fresh-16': '2012 Mario platform game released before New Super Mario Bros. U.',
  'fresh-18': 'Width, in pixels, of the original Mario sprite.',
  'kart-professor-1': 'The final course of MK8 Deluxe’s Spiny Cup.',
  'kart-professor-2': 'The first course of MK8 Deluxe’s Acorn Cup.',
  'kart-professor-3': 'Feather Cup course immediately after GCN Daisy Cruiser.',
  'kart-professor-4': 'The last course of MK8 Deluxe’s Fruit Cup.',
  'kart-professor-6': 'Moon Cup course immediately before 3DS Rainbow Road.',
  'kart-professor-7': 'Booster Course Pass wave that added the Spiny Cup.',
  'kart-professor-8': 'World race mode, alongside Knockout Tour, that supports up to 24 racers.',
  'expanded-36': 'Spiny Cup course just before SNES Bowser Castle 3.',
  'expanded-37': 'The final course of MK8 Deluxe’s Cherry Cup.',
  'expanded-38': 'MK8 Deluxe item available only in Battle mode.',
  'expanded-39': 'MK8 Deluxe item that gives a small boost each time it bites.',
  'fresh-33': 'One of the racers added in the final Booster Course Pass wave.',
  'fresh-34': 'The second course of MK8 Deluxe’s Acorn Cup.',
  'fresh-35': 'Propeller Cup course between GBA Snow Land and Sky-High Sundae.',
  'fresh-36': 'The opening Mushroom Cup course in Mario Kart World.',
};

export type MatchClue = { id: string; name: string; clue: string; difficulty: Difficulty; question: TriviaQuestion };
export const MATCH_CLUES: readonly MatchClue[] = Object.entries(CLUES).map(([id, clue]) => {
  const question = QUESTIONS.find(item => item.id === id);
  if (!question) throw new Error(`Missing matching source: ${id}`);
  return { id, name: question.answer, clue, difficulty: question.difficulty, question };
});

export const knowledgeLevel = (difficulty: Difficulty) => ['explorer', 'scientist', 'professor'].indexOf(difficulty);
